import { useEffect, useMemo, useRef, useState } from 'react'
import maplibregl, { type GeoJSONSource, type Map } from 'maplibre-gl'
import 'maplibre-gl/dist/maplibre-gl.css'
import { DESTINATION, START } from '../data/hiroshima'
import { destinationPoint } from '../lib/geo'
import { buildingShadowPolygons } from '../lib/shade'
import type { Building, BuildingDisplayMode, BuildingShadow, RoutePlan, ShadeResult, ValidationLocation, WorldMode } from '../types'

const style = 'https://tiles.openfreemap.org/styles/liberty'
const VISUAL_SHADOW_CORRIDOR_METERS = 120
const ownLayers = new Set(['route-lines', 'route-shaded', 'route-sunny', 'route-indeterminate', 'plateau-buildings-2d', 'plateau-buildings-3d', 'world-building-outline', 'world-shadows-fill', 'world-shadows-line', 'world-landmarks-circle', 'world-landmarks-label', 'debug-footprints-layer', 'debug-shadows-fill', 'debug-shadows-line', 'debug-selected-shadow-fill', 'debug-selected-shadow-line', 'debug-shadow-direction', 'debug-shadow-label', 'debug-points-layer'])
type DebugLayer = 'buildings' | 'shadows' | 'points'

const routeFeatures = (routes: RoutePlan[]) => ({ type: 'FeatureCollection' as const, features: routes.map((route) => ({ type: 'Feature' as const, properties: { kind: route.kind }, geometry: { type: 'LineString' as const, coordinates: route.coordinates.map(({ lng, lat }) => [lng, lat]) } })) })
const routeSegments = (result: ShadeResult | undefined, status?: 'shaded' | 'sunny' | 'indeterminate') => ({ type: 'FeatureCollection' as const, features: (result?.points ?? []).slice(1).flatMap((point, index) => !status || point.status === status ? [{ type: 'Feature' as const, properties: { status: point.status }, geometry: { type: 'LineString' as const, coordinates: [[result!.points[index].lng, result!.points[index].lat], [point.lng, point.lat]] } }] : []) })
function setSource(map: Map, id: string, data: GeoJSON.GeoJSON) { (map.getSource(id) as GeoJSONSource | undefined)?.setData(data) }
function buildingFeatures(buildings: Building[]) { return { type: 'FeatureCollection' as const, features: buildings.map((building) => ({ type: 'Feature' as const, properties: { id: building.id, height: building.heightMeters, heightSource: building.heightSource ?? 'sample', dataYear: building.dataYear ?? '', lod: building.lod ?? '' }, geometry: { type: 'Polygon' as const, coordinates: [[...building.footprint, building.footprint[0]].map(({ lng, lat }) => [lng, lat])] } })) } }
function nearRoute(building: Building, result: ShadeResult) { const latBuffer = VISUAL_SHADOW_CORRIDOR_METERS / 110_540; return building.footprint.some((vertex) => result.points.some((point) => Math.abs(point.lat - vertex.lat) < latBuffer && Math.abs(point.lng - vertex.lng) < latBuffer / Math.cos(point.lat * Math.PI / 180))) }
function shadowFeatures(buildings: Building[], result: ShadeResult | undefined) { if (!result || result.sunAltitude <= 3) return { type: 'FeatureCollection' as const, features: [] }; return { type: 'FeatureCollection' as const, features: buildings.filter((building) => nearRoute(building, result)).map((building) => ({ type: 'Feature' as const, properties: { id: building.id }, geometry: { type: 'MultiPolygon' as const, coordinates: buildingShadowPolygons(building, result.sunAltitude, result.sunBearing).map((polygon) => [[...polygon, polygon[0]].map(({ lng, lat }) => [lng, lat])]) } })) } }
function debugShadowFeatures(shadows: BuildingShadow[]) { return { type: 'FeatureCollection' as const, features: shadows.flatMap((shadow) => shadow.polygons.map((polygon, index) => ({ type: 'Feature' as const, properties: { id: shadow.buildingId, shadowLength: shadow.shadowLengthMeters, shadowBearing: shadow.shadowBearing, polygonIndex: index }, geometry: { type: 'Polygon' as const, coordinates: [[...polygon, polygon[0]].map(({ lng, lat }) => [lng, lat])] } }))) } }
function debugPointFeatures(result: ShadeResult | undefined) { return { type: 'FeatureCollection' as const, features: (result?.points ?? []).map((point) => ({ type: 'Feature' as const, properties: { status: point.status }, geometry: { type: 'Point' as const, coordinates: [point.lng, point.lat] } })) } }
function centerOf(building: Building) { const count = building.footprint.length || 1; return building.footprint.reduce((center, point) => ({ lng: center.lng + point.lng / count, lat: center.lat + point.lat / count }), { lng: 0, lat: 0 }) }
function directionFeatures(building: Building | undefined, shadow: BuildingShadow | undefined) { if (!building || !shadow || shadow.shadowLengthMeters <= 0) return { type: 'FeatureCollection' as const, features: [] }; const origin = centerOf(building); const tip = destinationPoint(origin, shadow.shadowBearing, shadow.shadowLengthMeters); return { type: 'FeatureCollection' as const, features: [{ type: 'Feature' as const, properties: {}, geometry: { type: 'LineString' as const, coordinates: [[origin.lng, origin.lat], [tip.lng, tip.lat]] } }, { type: 'Feature' as const, properties: { label: `影 ${shadow.shadowLengthMeters.toFixed(1)}m` }, geometry: { type: 'Point' as const, coordinates: [tip.lng, tip.lat] } }] } }
const landmarks = { type: 'FeatureCollection' as const, features: [{ name: '広島駅', position: START }, { name: '八丁堀', position: { lng: 132.4635, lat: 34.3958 } }, { name: '本通', position: { lng: 132.4591, lat: 34.3945 } }, { name: '原爆ドーム', position: { lng: 132.4531, lat: 34.3957 } }, { name: '平和記念公園', position: DESTINATION }].map(({ name, position }) => ({ type: 'Feature' as const, properties: { name }, geometry: { type: 'Point' as const, coordinates: [position.lng, position.lat] } })) }

function setBaseMode(map: Map, worldMode: WorldMode) {
  for (const layer of map.getStyle().layers ?? []) {
    if (ownLayers.has(layer.id)) continue
    if (layer.type === 'background') { map.setPaintProperty(layer.id, 'background-color', worldMode === 'shadow' ? '#04121c' : '#eef0ed'); continue }
    const retainWater = /water|river|stream/i.test(layer.id)
    try { map.setLayoutProperty(layer.id, 'visibility', worldMode === 'reality' || retainWater ? 'visible' : 'none') } catch { /* style layers without visibility remain unchanged */ }
  }
}
type Props = { routes: RoutePlan[]; selectedRoute: RoutePlan | undefined; shadeResult: ShadeResult | undefined; buildings: Building[]; debugShadows: BuildingShadow[]; debugEnabled: boolean; debugLayerVisibility: Record<DebugLayer, boolean>; validationLocation: ValidationLocation | undefined; buildingState: 'loading' | 'plateau' | 'sample'; buildingMode: BuildingDisplayMode; worldMode: WorldMode; is3d: boolean; onToggle3d: () => void; onCycleBuildingMode: () => void; onUnsupported: () => void }

export function MapCanvas({ routes, selectedRoute, shadeResult, buildings, debugShadows, debugEnabled, debugLayerVisibility, validationLocation, buildingState, buildingMode, worldMode, is3d, onToggle3d, onCycleBuildingMode, onUnsupported }: Props) {
  const node = useRef<HTMLDivElement>(null); const map = useRef<Map | null>(null); const [ready, setReady] = useState(false); const [selectedBuildingId, setSelectedBuildingId] = useState<string | null>(null)
  const selectedBuilding = useMemo(() => buildings.find((building) => building.id === selectedBuildingId), [buildings, selectedBuildingId]); const selectedShadow = useMemo(() => debugShadows.find((shadow) => shadow.buildingId === selectedBuildingId), [debugShadows, selectedBuildingId])
  useEffect(() => { if (!node.current) return undefined; if (!window.WebGLRenderingContext) { onUnsupported(); return undefined }; const instance = new maplibregl.Map({ container: node.current, style, center: [132.4633, 34.3967], zoom: 14.2, pitch: debugEnabled ? 0 : 42, bearing: debugEnabled ? 0 : -18 }); map.current = instance; instance.addControl(new maplibregl.NavigationControl(), 'bottom-right'); instance.addControl(new maplibregl.GeolocateControl({ positionOptions: { enableHighAccuracy: true }, trackUserLocation: true }), 'bottom-right'); instance.on('load', () => {
    instance.addSource('routes', { type: 'geojson', data: routeFeatures([]) }); instance.addLayer({ id: 'route-lines', type: 'line', source: 'routes', paint: { 'line-color': '#6a7a82', 'line-width': 3, 'line-opacity': .28 } }); instance.addSource('route-shaded-source', { type: 'geojson', data: routeSegments(undefined, 'shaded') }); instance.addLayer({ id: 'route-shaded', type: 'line', source: 'route-shaded-source', paint: { 'line-color': '#25e6d4', 'line-width': 8, 'line-opacity': .95, 'line-blur': .2 } }); instance.addSource('route-sunny-source', { type: 'geojson', data: routeSegments(undefined, 'sunny') }); instance.addLayer({ id: 'route-sunny', type: 'line', source: 'route-sunny-source', paint: { 'line-color': '#ffb547', 'line-width': 6, 'line-opacity': .96, 'line-dasharray': [1.2, 1.2] } }); instance.addSource('route-indeterminate-source', { type: 'geojson', data: routeSegments(undefined, 'indeterminate') }); instance.addLayer({ id: 'route-indeterminate', type: 'line', source: 'route-indeterminate-source', paint: { 'line-color': '#74838a', 'line-width': 5, 'line-opacity': .9, 'line-dasharray': [1, 1.4] } });
    instance.addSource('buildings', { type: 'geojson', data: buildingFeatures([]) }); instance.addLayer({ id: 'plateau-buildings-2d', type: 'fill', source: 'buildings', layout: { visibility: 'none' }, paint: { 'fill-color': '#315267', 'fill-opacity': .48 } }); instance.addLayer({ id: 'plateau-buildings-3d', type: 'fill-extrusion', source: 'buildings', layout: { visibility: 'none' }, paint: { 'fill-extrusion-color': '#183b4d', 'fill-extrusion-height': ['get', 'height'], 'fill-extrusion-opacity': .74 } }); instance.addLayer({ id: 'world-building-outline', type: 'line', source: 'buildings', layout: { visibility: 'none' }, paint: { 'line-color': '#254e5b', 'line-width': 1, 'line-opacity': .62 } });
    instance.addSource('shadows', { type: 'geojson', data: shadowFeatures([], undefined) }); instance.addLayer({ id: 'world-shadows-fill', type: 'fill', source: 'shadows', paint: { 'fill-color': '#0b5360', 'fill-opacity': .56, 'fill-outline-color': '#16b8ad' } }); instance.addLayer({ id: 'world-shadows-line', type: 'line', source: 'shadows', paint: { 'line-color': '#25e6d4', 'line-width': 1, 'line-opacity': .36 } }); instance.addSource('world-landmarks', { type: 'geojson', data: landmarks }); instance.addLayer({ id: 'world-landmarks-circle', type: 'circle', source: 'world-landmarks', paint: { 'circle-radius': 3, 'circle-color': '#d8fbf7', 'circle-opacity': .86 } }); instance.addLayer({ id: 'world-landmarks-label', type: 'symbol', source: 'world-landmarks', layout: { 'text-field': ['get', 'name'], 'text-size': 11, 'text-offset': [0, 1], 'text-anchor': 'top', 'text-allow-overlap': true }, paint: { 'text-color': '#d8fbf7', 'text-halo-color': '#04121c', 'text-halo-width': 1.2 } });
    instance.addSource('debug-footprints', { type: 'geojson', data: buildingFeatures([]) }); instance.addLayer({ id: 'debug-footprints-layer', type: 'line', source: 'debug-footprints', layout: { visibility: 'none' }, paint: { 'line-color': '#c5ccd2', 'line-width': 1.2, 'line-opacity': .9 } }); instance.addSource('debug-shadows', { type: 'geojson', data: debugShadowFeatures([]) }); instance.addLayer({ id: 'debug-shadows-fill', type: 'fill', source: 'debug-shadows', layout: { visibility: 'none' }, paint: { 'fill-color': '#123f68', 'fill-opacity': .2 } }); instance.addLayer({ id: 'debug-shadows-line', type: 'line', source: 'debug-shadows', layout: { visibility: 'none' }, paint: { 'line-color': '#3b6d98', 'line-width': 1, 'line-opacity': .35 } }); instance.addSource('debug-selected-shadow', { type: 'geojson', data: debugShadowFeatures([]) }); instance.addLayer({ id: 'debug-selected-shadow-fill', type: 'fill', source: 'debug-selected-shadow', layout: { visibility: 'none' }, paint: { 'fill-color': '#cb9cff', 'fill-opacity': .58 } }); instance.addLayer({ id: 'debug-selected-shadow-line', type: 'line', source: 'debug-selected-shadow', layout: { visibility: 'none' }, paint: { 'line-color': '#f0d0ff', 'line-width': 2.2 } }); instance.addSource('debug-direction', { type: 'geojson', data: directionFeatures(undefined, undefined) }); instance.addLayer({ id: 'debug-shadow-direction', type: 'line', source: 'debug-direction', layout: { visibility: 'none' }, paint: { 'line-color': '#ffe174', 'line-width': 2, 'line-dasharray': [1.2, 1.2] } }); instance.addLayer({ id: 'debug-shadow-label', type: 'symbol', source: 'debug-direction', layout: { visibility: 'none', 'text-field': ['get', 'label'], 'text-size': 12, 'text-offset': [0, 1], 'text-anchor': 'top', 'text-allow-overlap': true }, paint: { 'text-color': '#fff3b0', 'text-halo-color': '#071827', 'text-halo-width': 1.5 } }); instance.addSource('debug-points', { type: 'geojson', data: debugPointFeatures(undefined) }); instance.addLayer({ id: 'debug-points-layer', type: 'circle', source: 'debug-points', layout: { visibility: 'none' }, paint: { 'circle-radius': 3, 'circle-color': ['match', ['get', 'status'], 'shaded', '#20e3d1', 'sunny', '#ef8a3c', '#8492a0'], 'circle-stroke-color': '#071827', 'circle-stroke-width': 1 } });
    ;['world-building-outline', 'world-shadows-fill', 'world-shadows-line', 'route-lines', 'route-shaded', 'route-sunny', 'route-indeterminate', 'world-landmarks-circle', 'world-landmarks-label', 'debug-footprints-layer', 'debug-shadows-fill', 'debug-shadows-line', 'debug-selected-shadow-fill', 'debug-selected-shadow-line', 'debug-shadow-direction', 'debug-shadow-label', 'debug-points-layer'].forEach((id) => instance.moveLayer(id)); const selectFeature = (event: maplibregl.MapLayerMouseEvent) => { const id = event.features?.[0]?.properties?.id; if (typeof id === 'string') setSelectedBuildingId(id) }; ;['plateau-buildings-3d', 'plateau-buildings-2d', 'debug-footprints-layer', 'debug-shadows-fill', 'debug-shadows-line'].forEach((id) => instance.on('click', id, selectFeature)); new maplibregl.Marker({ color: '#25e6d4' }).setLngLat([START.lng, START.lat]).setPopup(new maplibregl.Popup().setText('出発：広島駅')).addTo(instance); new maplibregl.Marker({ color: '#ffb547' }).setLngLat([DESTINATION.lng, DESTINATION.lat]).setPopup(new maplibregl.Popup().setText('到着：平和記念公園')).addTo(instance); setReady(true) }); return () => { setReady(false); instance.remove(); map.current = null } }, [debugEnabled, onUnsupported])
  useEffect(() => { const instance = map.current; if (!ready || !instance) return; setSource(instance, 'routes', routeFeatures(routes)); setSource(instance, 'route-shaded-source', routeSegments(shadeResult, 'shaded')); setSource(instance, 'route-sunny-source', routeSegments(shadeResult, 'sunny')); setSource(instance, 'route-indeterminate-source', routeSegments(shadeResult, 'indeterminate')); setSource(instance, 'buildings', buildingFeatures(buildings)); setSource(instance, 'shadows', shadowFeatures(buildings, shadeResult)); setSource(instance, 'debug-footprints', buildingFeatures(buildings)); setSource(instance, 'debug-shadows', debugShadowFeatures(debugShadows)); setSource(instance, 'debug-selected-shadow', debugShadowFeatures(selectedShadow ? [selectedShadow] : [])); setSource(instance, 'debug-direction', directionFeatures(selectedBuilding, selectedShadow)); setSource(instance, 'debug-points', debugPointFeatures(shadeResult)) }, [ready, routes, shadeResult, buildings, debugShadows, selectedBuilding, selectedShadow])
  useEffect(() => { const instance = map.current; if (!ready || !instance) return; setBaseMode(instance, debugEnabled ? 'reality' : worldMode); const visible = (value: boolean) => value ? 'visible' : 'none'; const reality = !debugEnabled && worldMode === 'reality'; const shadow = !debugEnabled && worldMode === 'shadow'; instance.setLayoutProperty('plateau-buildings-3d', 'visibility', visible((reality && buildingMode === '3d') || (debugEnabled && debugLayerVisibility.buildings && buildingMode === '3d'))); instance.setLayoutProperty('plateau-buildings-2d', 'visibility', visible((reality && buildingMode === '2d') || (debugEnabled && buildingMode === '2d'))); instance.setLayoutProperty('world-building-outline', 'visibility', visible(shadow)); instance.setLayoutProperty('world-shadows-fill', 'visibility', visible(!debugEnabled)); instance.setLayoutProperty('world-shadows-line', 'visibility', visible(!debugEnabled)); instance.setLayoutProperty('world-landmarks-circle', 'visibility', visible(shadow)); instance.setLayoutProperty('world-landmarks-label', 'visibility', visible(shadow)); instance.setPaintProperty('world-shadows-fill', 'fill-opacity', shadow ? .56 : .16); instance.setPaintProperty('world-shadows-line', 'line-opacity', shadow ? .36 : .15); instance.setLayoutProperty('debug-footprints-layer', 'visibility', visible(debugEnabled && debugLayerVisibility.buildings)); ;['debug-shadows-fill', 'debug-shadows-line', 'debug-selected-shadow-fill', 'debug-selected-shadow-line', 'debug-shadow-direction', 'debug-shadow-label'].forEach((id) => instance.setLayoutProperty(id, 'visibility', visible(debugEnabled && debugLayerVisibility.shadows))); instance.setLayoutProperty('debug-points-layer', 'visibility', visible(debugEnabled && debugLayerVisibility.points)) }, [ready, buildingMode, debugEnabled, debugLayerVisibility, worldMode])
  useEffect(() => { const canvas = map.current?.getCanvas(); if (!canvas || debugEnabled || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return undefined; canvas.style.transition = 'opacity 420ms ease'; canvas.style.opacity = '.58'; const frame = window.requestAnimationFrame(() => { canvas.style.opacity = '1' }); return () => window.cancelAnimationFrame(frame) }, [worldMode, debugEnabled])
  useEffect(() => { const instance = map.current; if (!ready || !instance || !selectedRoute) return; const [first] = selectedRoute.coordinates; const bounds = selectedRoute.coordinates.reduce((current, point) => current.extend([point.lng, point.lat]), new maplibregl.LngLatBounds([first.lng, first.lat], [first.lng, first.lat])); instance.fitBounds(bounds, { padding: 80, maxZoom: 15, duration: 550 }) }, [ready, selectedRoute]); useEffect(() => { if (validationLocation && ready) map.current?.flyTo({ center: [validationLocation.position.lng, validationLocation.position.lat], zoom: validationLocation.zoom, duration: 550 }) }, [ready, validationLocation]); useEffect(() => { map.current?.easeTo({ pitch: is3d ? 42 : 0, bearing: is3d ? -18 : 0, duration: 420 }) }, [is3d])
  const buildingLabel = buildingMode === '3d' ? '建物 3D' : buildingMode === '2d' ? '建物 2D' : '建物 OFF'; const note = buildingState === 'loading' ? 'PLATEAU建物データを読み込み中…' : buildingState === 'sample' ? '実証用サンプル建物を表示中。' : 'PLATEAU広島市・2024年度建物データから推定。'
  return <div className={`map-wrap ${worldMode === 'shadow' && !debugEnabled ? 'map-shadow-world' : 'map-reality'}`}><div className="map" ref={node} aria-label="広島市中心部の地図" /><div className="map-tools"><button className="map-mode" onClick={onToggle3d} aria-pressed={is3d}>{is3d ? '3D' : '2D'}</button><button className="building-mode" onClick={onCycleBuildingMode} aria-label="建物表示を切り替え" aria-pressed={buildingMode !== 'off'}>{buildingLabel}</button></div>{debugEnabled && <div className="debug-map-legend"><span className="debug-legend-building" />建物 <span className="debug-legend-shadow" />推定影 <span className="debug-legend-shaded" />日陰経路点 <span className="debug-legend-sunny" />日なた経路点</div>}<p className="map-note">{note}</p>{debugEnabled && selectedBuilding && <aside className="debug-building-inspector" aria-live="polite"><strong>建物検証</strong><span>ID: {selectedBuilding.id}</span><span>採用高: {selectedBuilding.heightMeters.toFixed(1)}m（{selectedBuilding.heightSource ?? 'sample'}）</span><span>measuredHeight: {selectedBuilding.heightSource === 'measuredHeight' ? `${selectedBuilding.heightMeters.toFixed(1)}m` : '未採用'}</span><span>geometry_z_range: {selectedBuilding.heightSource === 'geometry_z_range' ? `${selectedBuilding.heightMeters.toFixed(1)}m` : '未採用'}</span><span>影長: {selectedShadow?.shadowLengthMeters.toFixed(1) ?? '0.0'}m / 方位: {selectedShadow?.shadowBearing.toFixed(1) ?? '-'}°</span><span>年度: {selectedBuilding.dataYear ?? '-'} / LOD: {selectedBuilding.lod ?? '-'}</span><span>日陰計算対象: {selectedShadow ? '対象' : '対象外'}</span></aside>}</div>
}
