import { useState } from 'react'
import type { ShadeResult, ValidationLocation } from '../types'

type Props = { result: ShadeResult | undefined; location: ValidationLocation | undefined; locations: ValidationLocation[]; onLocationChange: (id: string) => void; onHourChange: (hour: number) => void; buildRecord: (note: string) => string }
export function ShadeValidationPanel({ result, location, locations, onLocationChange, onHourChange, buildRecord }: Props) {
  const [note, setNote] = useState('')
  if (!result) return <section className="shade-validation"><strong>日陰検証モード</strong><span>経路と建物データを読み込み中…</span></section>
  const save = () => { const blob = new Blob([buildRecord(note)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `hikage-validation-${new Date().toISOString().replace(/[:.]/g, '-')}.json`; link.click(); URL.revokeObjectURL(url) }
  const copy = async () => { await navigator.clipboard?.writeText(buildRecord(note)) }
  return <section className="shade-validation" aria-label="日陰検証モード"><strong>日陰検証モード</strong><label>検証地点<select value={location?.id ?? ''} onChange={(event) => onLocationChange(event.target.value)}>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="validation-presets">{[9, 12, 15, 17].map((hour) => <button key={hour} onClick={() => onHourChange(hour)}>{hour}:00</button>)}</div><dl><div><dt>太陽高度 / 方位</dt><dd>{result.sunAltitude.toFixed(1)}° / {result.sunBearing.toFixed(1)}°</dd></div><div><dt>影方位 / 影ポリゴン</dt><dd>{result.audit.shadowBearing.toFixed(1)}° / {result.audit.shadowPolygonCount}</dd></div><div><dt>経路点（日陰 / 日なた / 判定不能）</dt><dd>{result.audit.routeSampleCount}（{result.audit.shadedPointCount} / {result.audit.sunnyPointCount} / {result.audit.indeterminatePointCount}）</dd></div><div><dt>推定日陰率 / 処理時間</dt><dd>{result.shadePercent.toFixed(1)}% / {result.audit.processingMilliseconds.toFixed(1)}ms</dd></div><div><dt>日陰計算候補建物</dt><dd>{result.audit.candidateBuildingCount}棟</dd></div></dl><label>現地メモ<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="写真番号・雲量・工事状況など" /></label><div className="validation-actions"><button onClick={copy}>JSONをコピー</button><button onClick={save}>JSONを保存</button></div><small>建物・青紫の影線をクリックすると、高さと影の計算値を表示する。グレー点は夜間・低太陽高度で判定不能。</small></section>
}
