import type { RouteKind, RoutePlan } from '../types'
import type { RouteMetrics } from '../lib/routeMetrics'

const distance = (meters: number) => `${Math.round(meters)}m`
const minutes = (seconds: number) => `${Math.max(1, Math.round(seconds / 60))}分`

export function ShadowRouteSummary({ route, routeKind, onRouteChange, metrics, isFallback, shadePercent }: { route: RoutePlan | undefined; routeKind: RouteKind; onRouteChange: (kind: RouteKind) => void; metrics: RouteMetrics; isFallback: boolean; shadePercent: number | undefined }) {
  return <section className="shadow-summary" aria-label="影渡りの結果"><div className="route-switch" role="tablist"><button role="tab" aria-selected={routeKind === 'shade'} className={routeKind === 'shade' ? 'selected' : ''} onClick={() => onRouteChange('shade')}>影渡り</button><button role="tab" aria-selected={routeKind === 'shortest'} className={routeKind === 'shortest' ? 'selected' : ''} onClick={() => onRouteChange('shortest')}>最短</button></div>{isFallback && <p className="sample-route">実証用サンプル経路を表示中</p>}<div className="summary-primary"><p>{routeKind === 'shade' ? '影を歩ける距離' : '到着まで'}</p><strong>{routeKind === 'shade' ? distance(metrics.totalShadeMeters) : `${Math.round((route?.durationSeconds ?? 0) / 60)}分`}</strong><span>{routeKind === 'shade' ? `到着目安 ${Math.max(1, Math.round((route?.durationSeconds ?? 0) / 60))}分` : `${distance(route?.distanceMeters ?? 0)} の経路`}</span></div><div className="summary-metrics"><p><b>日なたを{metrics.sunnyCrossings}回渡る</b><span>最大 {distance(metrics.maxSunnyCrossingMeters)}</span></p><p><b>{metrics.nextShadeDistanceMeters === 0 ? 'いま影の中です' : metrics.nextShadeDistanceMeters === null ? '次の影は未推定' : `次の影まで ${distance(metrics.nextShadeDistanceMeters)}`}</b><span>日なた 約{minutes(metrics.sunnySeconds)}</span></p></div><details><summary>影の道の詳細</summary><p>最長の影区間 {distance(metrics.longestShadeMeters)}。推定日陰率 {Math.round(shadePercent ?? 0)}%。建物形状と太陽位置からの推定で、樹木・屋根・現地工事は未反映。</p></details></section>
}
