import { useCallback, useEffect, useMemo, useState } from 'react'
import { IntroSequence } from './components/IntroSequence'
import { MapCanvas } from './components/MapCanvas'
import { MapErrorBoundary } from './components/MapErrorBoundary'
import { MapFallback } from './components/MapFallback'
import { ShadeValidationPanel } from './components/ShadeValidationPanel'
import { ShadowLegend } from './components/ShadowLegend'
import { ShadowRouteSummary } from './components/ShadowRouteSummary'
import { ShadowTimeControl } from './components/ShadowTimeControl'
import { WeatherPanel } from './components/WeatherPanel'
import { WorldModeToggle } from './components/WorldModeToggle'
import { validationLocations } from './data/validation'
import { demoBuildings } from './data/hiroshima'
import { useAsyncResource } from './hooks/useAsyncResource'
import { calculateRouteMetrics } from './lib/routeMetrics'
import { buildShadowAudit, calculateShade, selectShadeCandidateBuildings } from './lib/shade'
import { buildShadeValidationRecord } from './lib/shadeValidation'
import { fetchPlateauBuildings } from './services/buildings'
import { loadRoutes } from './services/routing'
import { fetchWeather } from './services/weather'
import type { BuildingDisplayMode, RouteKind, WorldMode } from './types'

type DebugLayer = 'buildings' | 'shadows' | 'points'
const nowRounded = () => { const date = new Date(); date.setMinutes(Math.ceil(date.getMinutes() / 10) * 10, 0, 0); return date }
const isShadeDebug = new URLSearchParams(window.location.search).get('debug') === 'shade'

export default function App() {
  const [departure, setDeparture] = useState(nowRounded); const [selected, setSelected] = useState<RouteKind>('shade'); const [worldMode, setWorldMode] = useState<WorldMode>('shadow'); const [is3d, setIs3d] = useState(!isShadeDebug); const [buildingMode, setBuildingMode] = useState<BuildingDisplayMode>(isShadeDebug ? '2d' : 'off'); const [debugLayers, setDebugLayers] = useState({ buildings: true, shadows: true, points: true }); const [validationLocationId, setValidationLocationId] = useState(validationLocations[0].id); const [mapReady, setMapReady] = useState(false); const [mapFailure, setMapFailure] = useState<Error | null>(null); const [mapKey, setMapKey] = useState(0); const [isRecalculating, setIsRecalculating] = useState(false)
  const weather = useAsyncResource(fetchWeather); const routesResource = useAsyncResource(loadRoutes); const buildingsResource = useAsyncResource(fetchPlateauBuildings); const routes = routesResource.data?.routes ?? []; const buildingState = buildingsResource.data ? 'plateau' : buildingsResource.error ? 'sample' : 'loading'; const buildings = buildingsResource.data?.buildings ?? (buildingState === 'sample' ? demoBuildings : []); const results = useMemo(() => Object.fromEntries(routes.map((route) => [route.id, calculateShade(route, buildings, departure)])), [routes, buildings, departure]); const selectedRoute = routes.find((route) => route.kind === selected) ?? routes[0]; const selectedResult = selectedRoute ? results[selectedRoute.id] : undefined; const metrics = useMemo(() => calculateRouteMetrics(selectedResult), [selectedResult]); const debugShadows = useMemo(() => !isShadeDebug || !selectedResult ? [] : buildShadowAudit(selectShadeCandidateBuildings(buildings, selectedResult.points), selectedResult.sunAltitude, selectedResult.sunBearing), [buildings, selectedResult]); const validationLocation = validationLocations.find((location) => location.id === validationLocationId)
  const selectRoute = useCallback((kind: RouteKind) => setSelected(kind), []); const cycleBuildingMode = useCallback(() => setBuildingMode((mode) => mode === '3d' ? '2d' : mode === '2d' ? 'off' : '3d'), []); const setDebugLayer = useCallback((layer: DebugLayer, visible: boolean) => setDebugLayers((current) => ({ ...current, [layer]: visible })), []); const reportMapFailure = useCallback((error?: Error) => { setMapReady(false); setMapFailure(error ?? new Error('WebGL map initialization failed')) }, []); const handleMapReady = useCallback(() => setMapReady(true), []); const retryMap = useCallback(() => { setMapFailure(null); setMapReady(false); setMapKey((key) => key + 1) }, []); const setMinutes = useCallback((minutes: number) => { setIsRecalculating(true); setDeparture((date) => { const next = new Date(date); next.setHours(Math.floor(minutes / 60), minutes % 60, 0, 0); return next }) }, []); const toggleWorld = useCallback((mode: WorldMode) => { setWorldMode(mode); if (mode === 'reality' && buildingMode === 'off') setBuildingMode('3d') }, [buildingMode])
  useEffect(() => { if (!isRecalculating) return undefined; const id = window.setTimeout(() => setIsRecalculating(false), 380); return () => window.clearTimeout(id) }, [isRecalculating, results])
  const mapCanvas = mapFailure ? <MapFallback onRetry={retryMap} /> : <MapErrorBoundary resetKey={mapKey} onError={reportMapFailure} fallback={<MapFallback onRetry={retryMap} />}><MapCanvas key={mapKey} routes={routes} selectedRoute={selectedRoute} shadeResult={selectedResult} buildings={buildings} debugShadows={debugShadows} debugEnabled={isShadeDebug} debugLayerVisibility={debugLayers} validationLocation={isShadeDebug ? validationLocation : undefined} buildingState={buildingState} buildingMode={buildingMode} worldMode={isShadeDebug ? 'reality' : worldMode} is3d={is3d} onReady={handleMapReady} onToggle3d={() => setIs3d((current) => !current)} onCycleBuildingMode={cycleBuildingMode} onUnsupported={reportMapFailure} /></MapErrorBoundary>
  const loadingMessage = !mapReady ? '広島の建物を呼び出しています' : buildingState === 'loading' ? '太陽の位置を確認しています' : isRecalculating ? '影を動かしています' : routesResource.loading ? '影の道を探しています' : null
  if (isShadeDebug) return <main className="debug-app"><aside className="debug-panel"><header><div className="brand-mark">◒</div><div><p>SHADE CALCULATION LAB</p><h1>日陰ナビ</h1></div></header><label className="debug-time">出発時刻<input type="time" step="600" value={`${String(departure.getHours()).padStart(2, '0')}:${String(departure.getMinutes()).padStart(2, '0')}`} onChange={(event) => { const [hours, minutes] = event.target.value.split(':').map(Number); setMinutes(hours * 60 + minutes) }} /></label><WeatherPanel resource={weather} />{routesResource.loading && <p className="muted">徒歩経路を取得中…</p>}{routesResource.error && <p className="notice">{routesResource.error}</p>}{routesResource.data?.fallbackReason && <p className="notice">実証用サンプル経路：{routesResource.data.fallbackReason}</p>}<ShadeValidationPanel result={selectedResult} location={validationLocation} locations={validationLocations} layerVisibility={debugLayers} onLayerVisibilityChange={setDebugLayer} onLocationChange={setValidationLocationId} onHourChange={(hour) => setMinutes(hour * 60)} buildRecord={(note) => selectedRoute && selectedResult ? JSON.stringify(buildShadeValidationRecord(selectedRoute, selectedResult, buildingsResource.data?.metadata, departure, note), null, 2) : '{}'} /><p className="debug-data-note">建物：{buildingState === 'plateau' ? `PLATEAU広島市 ${buildingsResource.data?.metadata.dataYear}年度` : buildingState === 'loading' ? '読込中' : '実証用サンプル'}</p></aside><section className="debug-map-area">{mapCanvas}</section></main>
  return <main className="shadow-app"><section className="world-map-area">{mapCanvas}{loadingMessage && <div className="world-loading" role="status">{loadingMessage}</div>}</section><header className="world-header"><div className="brand"><span className="brand-mark">◒</span><div><p>日陰ナビ</p><h1>影の広島</h1><span>太陽の下では見えない、もう一つの街。</span></div></div><WorldModeToggle mode={worldMode} onChange={toggleWorld} /></header><div className="journey-chip" aria-label="経路"><button aria-label="出発地を変更">広島駅</button><span>→</span><button aria-label="目的地を変更">平和記念公園</button></div><aside className="world-controls"><ShadowTimeControl value={departure} onCommit={setMinutes} /><div className="world-status"><span>{weather.data?.temperature == null ? '気象を取得中' : `${weather.data.temperature.toFixed(1)}°C / 体感 ${weather.data.apparentTemperature?.toFixed(1) ?? '—'}°C`}</span><span>{buildingState === 'plateau' ? 'PLATEAU 2024・建物影推定' : buildingState === 'loading' ? '建物データ読込中' : '建物は実証用サンプル'}</span></div>{routesResource.loading && <p className="world-notice">徒歩経路を取得中…</p>}{routesResource.error && <p className="world-notice">{routesResource.error}</p>}{routesResource.data?.fallbackReason && <p className="world-notice">実証用サンプル経路：{routesResource.data.fallbackReason}</p>}</aside><aside className="world-summary"><ShadowRouteSummary route={selectedRoute} routeKind={selected} onRouteChange={selectRoute} metrics={metrics} isFallback={routesResource.data?.isFallback ?? true} shadePercent={selectedResult?.shadePercent} /><p className="world-disclaimer">建物形状と太陽位置から推定。樹木・屋根・現地工事は未反映で、実際の日陰と異なる場合があります。</p></aside><ShadowLegend /><IntroSequence /></main>
}
