import { useCallback, useMemo, useState } from 'react'
import { MapCanvas } from './components/MapCanvas'
import { RouteResult } from './components/RouteResult'
import { WeatherPanel } from './components/WeatherPanel'
import { demoBuildings } from './data/hiroshima'
import { useAsyncResource } from './hooks/useAsyncResource'
import { calculateShade } from './lib/shade'
import { loadRoutes } from './services/routing'
import { fetchWeather } from './services/weather'
import type { RouteKind } from './types'
const nowRounded = () => { const date = new Date(); date.setMinutes(Math.ceil(date.getMinutes() / 10) * 10, 0, 0); return date }
export default function App() { const [departure, setDeparture] = useState(nowRounded); const [selected, setSelected] = useState<RouteKind>('shade'); const [is3d, setIs3d] = useState(true); const [webglError, setWebglError] = useState(false); const weather = useAsyncResource(fetchWeather); const routesResource = useAsyncResource(loadRoutes); const routes = routesResource.data?.routes ?? []; const results = useMemo(() => Object.fromEntries(routes.map((route) => [route.id, calculateShade(route, demoBuildings, departure)])), [routes, departure]); const selectedRoute = routes.find((route) => route.kind === selected) ?? routes[0]; const selectRoute = useCallback((kind: RouteKind) => setSelected(kind), []); const localTime = `${String(departure.getHours()).padStart(2, '0')}:${String(departure.getMinutes()).padStart(2, '0')}`; const setTime = (value: string) => { const [hours, minutes] = value.split(':').map(Number); setDeparture((date) => { const next = new Date(date); next.setHours(hours, minutes, 0, 0); return next }) }
  if (webglError) return <main className="webgl-fallback"><h1>日陰ナビ</h1><p>このブラウザでは3D地図（WebGL）を表示できません。</p><p>WebGLを有効にするか、対応ブラウザでお試しください。気象・日陰推定の表示は準備中です。</p></main>
  return <main className="app"><aside className="panel"><header><div className="brand-mark">◒</div><div><p>HIROSHIMA SHADE ROUTING</p><h1>日陰ナビ</h1></div></header><section className="journey"><div><span>出発地</span><strong>広島駅</strong></div><div className="journey-line" /><div><span>到着地</span><strong>平和記念公園</strong></div></section><label className="time-control"><span>出発時刻</span><input type="time" step="600" value={localTime} onChange={(event) => setTime(event.target.value)} /><small>10分単位・日陰率を再計算</small></label><WeatherPanel resource={weather} />{routesResource.loading && <p className="muted">徒歩経路を取得中…</p>}{routesResource.error && <p className="notice">{routesResource.error}</p>}{routes.length > 0 && <RouteResult routes={routes} results={results} selected={selected} onSelect={selectRoute} isFallback={routesResource.data?.isFallback ?? true} />}<button className="start-button" onClick={() => window.alert('案内開始は次の実装で現在地追従に対応します。')}>案内を開始</button><p className="disclaimer">実証版：涼しさ・安全を保証するものではありません。</p></aside><section className="map-area"><MapCanvas routes={routes} selectedRoute={selectedRoute} shadeResult={selectedRoute ? results[selectedRoute.id] : undefined} departure={departure} is3d={is3d} onToggle3d={() => setIs3d((current) => !current)} onUnsupported={() => setWebglError(true)} /></section></main> }
